---
title: "dataVis"
output: html_document
date: "2024-03-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse, wdnr.fmdb, wdnr.gis, lubridate, here)
```

Let's start with lakes that have PEs for walleye
browseVignettes("wdnr.fmdb")

```{r}
wye.pe<-read_csv(here::here("data","popest2023.csv"))%>%
  dplyr::select(WBIC:Year)%>%
  filter(Model%in%c(0:4))%>%
  rename("wbic"=WBIC,
         "year"=Year)

wbics<-unique(wye.pe$wbic)

lakeChar<-get_fmdb_lakechar()%>%
  filter(wbic%in%wbics)

creel_counts<-get_creel_counts(wbic=wbics[1:100])
creel_counts2<-get_creel_counts(wbic=wbics[101:200])
creel_counts3<-get_creel_counts(wbic=wbics[201:300])
creel_counts4<-get_creel_counts(wbic=wbics[301:411])

all_counts<-rbind.data.frame(creel_counts, creel_counts2, creel_counts3, creel_counts4)
creel_eff<-sum_monthly_creel_effort(all_counts)

creel_fish<-get_creel_fish_data(wbic=wbics[1:100])
creel_fish2<-get_creel_fish_data(wbic=wbics[101:200])
creel_fish3<-get_creel_fish_data(wbic=wbics[201:300])
creel_fish4<-get_creel_fish_data(wbic=wbics[301:411])

all_fish<-rbind.data.frame(creel_fish, creel_fish2, creel_fish3, creel_fish4)

creel_int<-get_creel_int_party(wbic=wbics[1:100])
creel_int2<-get_creel_int_party(wbic=wbics[101:200])
creel_int3<-get_creel_int_party(wbic=wbics[201:300])
creel_int4<-get_creel_int_party(wbic=wbics[301:411])

all_int<-rbind.data.frame(creel_int, creel_int2, creel_int3, creel_int4)


creel_harv_year<-calc_creel_harvest_rates(all_fish, grouping=c("year","wbic"))
creel_harv_month<-calc_creel_harvest_rates(all_fish, grouping=c("year","month","wbic"))

# output includes total catch rate, directed catch rate, and mean (+ same for harvest)

harv_year_wye<-creel_harv_year%>%
  filter(species=="walleye")%>%
  dplyr::select(year, wbic, spp.catch.rate, spp.harvest.rate, catch.rate.var, harvest.rate.var, total.spp.hours, total.spp.catch)%>%
  left_join(wye.pe, by=c("wbic","year"))%>%
  left_join(lakeChar[,c("wbic","lat","long","lake.area","wae.code")], by="wbic")%>%
  mutate(wye.pop.density=pe/lake.area,
         wbic=as.factor(wbic))
```

plot annual PE vs targeted catch rate

```{r}
ggplot(harv_year_wye, aes(x=log(wye.pop.density), y=log(spp.catch.rate+.01)))+
  geom_point(aes(color=wbic))+
  geom_smooth(method="lm")+
  theme(legend.position="none")

write.csv(harv_year_wye, here::here("data","pe.cpue.walleye.csv"))
```

How many obs per lake?

```{r}
nYears<-harv_year_wye%>%
  group_by(wbic)%>%
  summarize(nYears=length(unique(year)))%>%
  filter(nYears>3)
```

```{r}
mult_years<-harv_year_wye%>%
  filter(wbic%in%nYears$wbic)

ggplot(mult_years, aes(x=wye.pop.density, y=spp.catch.rate))+
  geom_point(aes(color=wbic))+
  geom_smooth(method="loess")+
  theme(legend.position="none")

  
```


Now look by month

```{r}
harv_month_wye<-creel_harv_month%>%
  filter(species=="walleye")%>%
  dplyr::select(year, month, wbic, spp.catch.rate, spp.harvest.rate, catch.rate.var, harvest.rate.var, total.spp.hours, total.spp.catch)%>%
  left_join(wye.pe, by=c("wbic","year"))%>%
  left_join(lakeChar[,c("wbic","lat","long","lake.area","wae.code")], by="wbic")%>%
  mutate(wye.pop.density=pe/lake.area,
         wbic=as.factor(wbic))

ggplot(harv_month_wye, aes(x=month, y=spp.catch.rate))+
  geom_point(aes(color=wbic))+
  theme(legend.position="none")

```

Now trip-level creel data. Already have all_fish

```{r}


indiv_catch<-all_fish%>%
  filter(trip.complete=="y")%>%
  filter(species=="walleye")%>%
  mutate(across(start.time:not.fishing.amt, as.character))%>%
  mutate(across(all_of(c("start.time","not.fishing.amt")), ~ifelse(.x=="0","0000", .x)))%>%
  mutate(across(start.time:not.fishing.amt, ~paste0(substr(.x, 1, 2), ":", substr(.x, 3, 4))))%>%
  mutate(across(start.time:end.time, ~ymd_hm(paste(sample.date, .x, sep=" "))))%>%
  mutate(not.fishing.amt=as.numeric(hm(not.fishing.amt)))%>%
  mutate(hours.fishing=as.numeric(((end.time-start.time)/3600)-(not.fishing.amt/3600))*(fished.perc/100))%>%
  dplyr::select(!c(unattended.line:interview.comment, troll.elapsed.time, troll.row.flag))%>%
  filter(hours.fishing>0)%>%
  mutate(anglerHours=hours.fishing*anglers,
         cpue=caught/anglerHours,
         hpue=kept/anglerHours)%>%
  # now join on PEs and lake characteristics
  left_join(wye.pe, by=c("wbic","year"))%>%
  left_join(lakeChar[,c("wbic","lat","long","lake.area","wae.code","max.depth","shore.length")], by="wbic")%>%
  mutate(pop.density=pe/lake.area)
  
write.csv(indiv_catch, here::here("data","indiv.level.cpue.pe.csv"))    
```


```{r}
ggplot(indiv_catch)+
  geom_point(aes(x=pop.density, y=cpue))

# some odd outliers here, dropping cpue>50
```
```{r}
indiv_catch<-indiv_catch%>%
  filter(cpue<50)%>%
  mutate(wbic=as.factor(wbic))%>%
  mutate(ln.cpue=log(cpue+0.01),
         ln.pop.density=log(pop.density+0.01))

ggplot(indiv_catch)+
  geom_point(aes(x=pop.density, y=cpue, color=wae.code))
  theme(legend.position="none")

```

```{r}
ggplot(indiv_catch)+
  geom_point(aes(x=ln.pop.density, y=ln.cpue, color=wbic))+
  theme(legend.position="none")

```
lots of zero values, which isn't ideal. hurdle model is probably appropriate, but starting with linear for slimplicity

```{r}
ggplot(indiv_catch)+
  geom_point(aes(x=year, y=cpue, color=as.factor(wbic)))+
  theme(legend.position="none")
```

