---
title: "data vis lmb dnr"
output: html_document
date: "2024-03-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse, wdnr.fmdb, wdnr.gis, lubridate, here)
```

Let's start with lakes that have PEs for walleye
browseVignettes("wdnr.fmdb")

Sticking with this--these lakes will have creel survey data and electrofishign surveys, which will give efcpue

```{r}
#  keeping this just for list of wbics
#  wye.pe<-read_csv(here::here("data","popest2023.csv"))%>%
#    dplyr::select(WBIC:Year)%>%
#    filter(Model%in%c(0:4))%>%
#    rename("wbic"=WBIC,
#           "year"=Year)
# 
# wbics<-unique(wye.pe$wbic)

creel_surveys_all<-get_creel_surveys()
wbics<-unique(creel_surveys_all$wbic)

lakeChar<-get_fmdb_lakechar()%>%
  filter(wbic%in%wbics)

creel_counts<-get_creel_counts(wbic=wbics[1:100])
creel_counts2<-get_creel_counts(wbic=wbics[101:200])
creel_counts3<-get_creel_counts(wbic=wbics[201:312])


all_counts<-rbind.data.frame(creel_counts, creel_counts2, creel_counts3)
#creel_eff<-sum_monthly_creel_effort(all_counts)

creel_fish<-get_creel_fish_data(wbic=wbics[1:100])
creel_fish2<-get_creel_fish_data(wbic=wbics[101:200])
creel_fish3<-get_creel_fish_data(wbic=wbics[201:312])

all_fish<-rbind.data.frame(creel_fish, creel_fish2, creel_fish3)%>%
  mutate(across(.cols=c("fished.perc","caught","kept","anglers"), as.numeric))

electro_effort<-get_fmdb_efforts(wbic=wbics[1:100])
electro_effort2<-get_fmdb_efforts(wbic=wbics[101:200])
electro_effort3<-get_fmdb_efforts(wbic=wbics[201:312])

all_electro_effort<-rbind.data.frame(electro_effort, electro_effort2, electro_effort3)

creel_int<-get_creel_int_party(wbic=wbics[1:100])
creel_int2<-get_creel_int_party(wbic=wbics[101:200])
creel_int3<-get_creel_int_party(wbic=wbics[201:312])

all_int<-rbind.data.frame(creel_int, creel_int2, creel_int3)

fish_raw<-get_fmdb_fishraw(wbic=wbics[1:100])
fish_raw2<-get_fmdb_fishraw(wbic=wbics[101:200])
fish_raw3<-get_fmdb_fishraw(wbic=wbics[201:312])

all_fish_raw<-rbind.data.frame(fish_raw, fish_raw2, fish_raw3)

creel_harv_year<-calc_creel_harvest_rates(all_fish, grouping=c("year","wbic"))
creel_harv_month<-calc_creel_harvest_rates(all_fish, grouping=c("year","month","wbic"))

all_fish_lmb_wye<-all_fish_raw%>%
  filter(species%in%c("walleye","largemouth_bass"))

electro_cpe<-calc_cpe(all_electro_effort, all_fish_lmb_wye)
write.csv(electro_cpe, here::here("data","dnr.ef.cpe.walleye.lmb.csv"))

electro_cpe_km<-electro_cpe%>%
  filter(gear=="boom_shocker")%>%
  mutate(total_effort_km=total_effort*1.61,
         cpe_km=total_catch/total_effort_km)%>%
  filter(total_effort_km>1)%>%
  # need an average of lake year ef cpe
  group_by(wbic, year)%>%
  summarize(mean_cpe_km=mean(cpe_km),
            sd_cpe_km=sd(cpe_km),
            n_ef_surveys=n())%>%
  ungroup()

# output includes total catch rate, directed catch rate, and mean (+ same for harvest)

harv_year_lmb<-creel_harv_year%>%
  filter(species=="largemouth_bass")%>%
  dplyr::select(year, wbic, spp.catch.rate, spp.harvest.rate, catch.rate.var, harvest.rate.var, total.spp.hours, total.spp.catch)%>%
  left_join(electro_cpe_km, by=c("wbic","year"))%>%
  left_join(lakeChar[,c("wbic","lat","long","lake.area","shore.length")], by="wbic")%>%
  mutate(wbic=as.factor(wbic))%>%
  filter(!is.na(mean_cpe_km)&!is.nan(spp.catch.rate))
```

plot annual PE vs targeted catch rate

```{r}

ggplot(harv_year_lmb, aes(x=mean_cpe_km, y=spp.catch.rate))+
  geom_point(aes(color=wbic))+
  geom_smooth(method="loess")+
  theme(legend.position="none")

ggplot(harv_year_lmb, aes(x=log(mean_cpe_km), y=log(spp.catch.rate+.01)))+
  geom_point(aes(color=wbic))+
  geom_smooth(method="lm")+
  theme(legend.position="none")

write.csv(harv_year_lmb, here::here("data","ef.cpe.cpue.lmb.csv"))
```

How many obs per lake?

```{r}
nYears<-harv_year_lmb%>%
  group_by(wbic)%>%
  summarize(nYears=length(unique(year)))%>%
  filter(nYears>3)
nYears
```



Now trip-level creel data. Already have all_fish


```{r}


indiv_catch<-all_fish%>%
  filter(species=="largemouth_bass")%>%
  filter(trip.complete=="y")%>%
  mutate(across(start.time:not.fishing.amt, as.character))%>%
  mutate(across(all_of(c("start.time","not.fishing.amt")), ~ifelse(.x=="0","0000", .x)))%>%
  mutate(across(start.time:not.fishing.amt, ~paste0(substr(.x, 1, 2), ":", substr(.x, 3, 4))))%>%
  mutate(across(start.time:end.time, ~ymd_hm(paste(sample.date, .x, sep=" "))))%>%
  mutate(not.fishing.amt=as.numeric(hm(not.fishing.amt)))%>%
  mutate(hours.fishing=as.numeric(((end.time-start.time)/3600)-(not.fishing.amt/3600))*(fished.perc/100))%>%
  dplyr::select(!c(unattended.line:interview.comment, troll.elapsed.time, troll.row.flag))%>%
  filter(hours.fishing>0)%>%
  mutate(anglerHours=hours.fishing*anglers,
         cpue=caught/anglerHours,
         hpue=kept/anglerHours,
         wbic=as.factor(wbic))%>%
  # now join on PEs and lake characteristics
  left_join(harv_year_lmb[,c("wbic","year","mean_cpe_km","sd_cpe_km", "n_ef_surveys", "lat", "long", "lake.area", "shore.length")], by=c("wbic","year"))%>%
  # filtering to cpue<20 fish per angler hour. 
  filter(cpue<=20)%>%
  filter(!is.na(mean_cpe_km))
  
write.csv(indiv_catch, here::here("data","indiv.level.lmb.cpue.ef.cpe.csv"))    
```


```{r}
ggplot(indiv_catch)+
  geom_point(aes(x=mean_cpe_km, y=cpue))

# some odd outliers here, dropping cpue>50
```
```{r}
indiv_catch<-indiv_catch%>%
  mutate(wbic=as.factor(wbic))%>%
  mutate(ln.cpue=log(cpue+0.01),
         ln.mean.cpe.km=log(mean_cpe_km+0.01))

ggplot(indiv_catch)+
  geom_point(aes(x=ln.mean.cpe.km, y=ln.cpue))
  theme(legend.position="none")

```
